---
version: '3.7'

networks:
  xes-platform-network:
    name: xes-platform-network

services:
  node-balance-retriever:
    build:
      .
    container_name: xes_node-node-balance-retriever
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: http://172.17.0.1:1323
      PROXEUS_ETH_CLIENT_URL: "${PROXEUS_ETH_CLIENT_URL:-https://ropsten.infura.io/v3/}"
      PROXEUS_INFURA_API_KEY: ${PROXEUS_INFURA_API_KEY}
      SERVICE_SECRET: secret
      SERVICE_PORT: 8012
      SERVICE_URL: http://localhost:8012
      TZ: Europe/Zurich
    ports:
      - "8012:8012"
